apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-docker-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels: 
        app: my-app
        env: development
    spec:                
      containers: 
      - name: my-app
        image: gcr.io/opencenus-node/nodejs-docker-app:v3
        ports:
        - containerPort: 3000
